### ISSUE TITLE
Greymane Description

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/heroes-data#15]
`Gamestrings > enus > unit > description > Greymane` reads:

> "A high damage Assassin that wears down enemies from afar and dives in for the kill.<n/><n/><img path=\"@UI/StormTalentInTextArmorIcon\" alignment=\"uppermiddle\" color=\"BBBBBB\" width=\"20\" height=\"22\"/><c val=\"bfd4fd\">10 Armor (in Worgen Form)</c>"

I assume the other tags and text are bleed-over from another part of the game data?

**Comment by koliva8245** [comment]
What's the problem? The description is correct.

**Comment by MGatner** [comment]
It's the only hero unit description with an `img` or `c` tag so I assumed it was an error. Those are intentional?

**Comment by koliva8245** [comment]
Yes. Other heroes had passive armor one point in time as well.
![image](https://user-images.githubusercontent.com/8988906/103182190-2d173f00-486f-11eb-8f0a-3760b61b1266.png)

**Comment by MGatner** [comment]
Gotcha! I recall that, for some reason I thought it was part of their trait. Thanks for the response.
