### ISSUE TITLE
Blank versions

### ISSUE THREAD

**Issue by MGatner** [HeroesToolChest/heroes-data#3]
A number of the patch folders are empty. Do you plan to fill these? Would raw data history on **heroes-talents** be helpful, despite the format differences?

E.g. 2.48.0.76389

**Comment by koliva8245** [comment]
I explained it in the readme. I'm unable to.

**Comment by MGatner** [comment]
Ah gotcha, understand that now. No worries, having any previous ones already exceeded my original expectations!

FYI the plan is to retroactively purge HDP data from heroes-talents to save space. I'm not sure what kind of archives you keep but if there's anything in there that would be helpful please grab it before we do. Probably still a week or so out.
